create home page
20210502-FE/Linevych_Boon_market pull request #1
Opened 2021-06-14 20:54 UTC by Roman240594

2021-07-04 15:22 UTC, JuliaSavych requested changes

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +    <header class="header">
чому ти завжди об'єднюєш хедер і банер? це різні елементи

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +        <div class="header__sticky">
це top-banner окремий елемент від хедера

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    height: 52px;
для чого фіксована висота?

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +                <ul class="header__items flex">
яким чином ця навігація відноситься до хедера?

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +        <section class="table">
![Screenshot from 2021-07-04 18-11-39](https://user-images.githubusercontent.com/19241160/124390239-4c49ca00-dcf3-11eb-8973-3ebb6ea01953.png)
ця елемент банера позиціонований, а не main

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +                <h5 class="info-work__sup-title text-uppercase">
subtitle

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    margin: 0 30px;
add columns with padding

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    padding: 73px 0 34px;
чому верхій відступ ти даєш тайтлу а не цілій секції?

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    padding: 155px 40px;
для чого падінг побоках, якщо у тебе .container ітак обмежує контент?

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    padding: 83px 0 107px;
верхня і нижні відсути мають бути у секції, а не у елементів (як тут верхній)

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +                <li class="goods__item"><a class="goods__link" href="#"><img class="goods__img"
тут посилання сплюснулося
display: block

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    padding:0 16px 90px;
а ось тут непонятний нижній падінг, який мав би бути у секції

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +            <div class="conteiner">
.container

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +                    <input class="connection__form-name" type="text" placeholder="First name">
для чого тут margin-left?

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +            <div class="footer-right-right">
whaaat?

2021-07-04 15:22 UTC, JuliaSavych commented on index.html
> +            <div class="footer-right-right">
.footer__about

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    margin-left: auto;
margin-left: auto; ?
чому батьківському не дати display: flex і не вирівняти justify-content: flex-end

2021-07-04 15:22 UTC, JuliaSavych commented on assets/css/style.css
> +    text-align: end;
вище стиль  text-align: center;

2021-07-05 14:53 UTC, Roman240594 commented on assets/css/style.css
> +    height: 52px;
При ховерному ефекті збільшується шрифт і в результаті цього нижні блоки звуваються, тому задав фіксовану висоту

2021-07-07 07:39 UTC, Roman240594 commented on index.html
> +                <h5 class="info-work__sup-title text-uppercase">
sup-title - це я писав як надзаголовок

2021-07-07 07:58 UTC, Roman240594 commented on index.html
> +                <li class="goods__item"><a class="goods__link" href="#"><img class="goods__img"
goods__link задати display:block?

2021-10-11 12:14 UTC, merged